version: 2
updates:
  - package-ecosystem: docker
    directory: /services/Archival/FilterLists.Archival.Api
    schedule:
      interval: daily
  - package-ecosystem: nuget
    directory: /services/Archival/FilterLists.Archival.Api
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /services/Directory/FilterLists.Directory.Api
    schedule:
      interval: daily
  - package-ecosystem: nuget
    directory: /services/Directory/FilterLists.Directory.Api
    schedule:
      interval: daily
  - package-ecosystem: nuget
    directory: /services/Directory/FilterLists.Directory.Infrastructure.Migrations.Tests
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /web
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: daily
