trigger:
  - docker-devops

pool:
  vmImage: "Ubuntu-16.04"

variables:
  buildConfiguration: "Release"

steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: "dotnet build $(buildConfiguration)"
