version: "3.7"

services:
  agent:
    image: collinbarrett2/filterlists.agent:test-agent
    build:
      context: .
      dockerfile: agent/FilterLists.Agent/Dockerfile
      target: test-agent
    networks:
      - test-agent
    volumes:
      - test-agent-results:/app/tests/FilterLists.Agent.Tests/TestResults

networks:
  test-agent:

volumes:
  test-agent-results:
    external: true
