version: "3.7"

services:
  api:
    image: collinbarrett/filterlists.api:test-services
    build:
      context: .
      dockerfile: src/FilterLists.Api/Dockerfile
      target: test-services
    networks:
      - test-services
    volumes:
      - test-services-results:/app/tests/FilterLists.Services.Tests/TestResults

networks:
  test-services:
  
volumes:
  test-services-results:
    external: true
