# for integration testing directory migrations

version: "3.7"

services:
  directory-migrations-tests:
    build:
      context: ./services
      dockerfile: Directory/FilterLists.Directory.Api/migrate.Dockerfile
      target: test-migrations
    volumes:
      - directory-migrations-tests-results:/FilterLists.Directory.Infrastructure.Migrations.Tests/TestResults
    depends_on:
      - directory-db
    environment:
      ConnectionStrings__DirectoryConnection: ${DIRECTORY_CONNECTION_STRING}

  directory-db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DIRECTORY_DB_USER}
      POSTGRES_PASSWORD: ${DIRECTORY_DB_PASSWORD}
      POSTGRES_DB: ${DIRECTORY_DB_DATABASE}

volumes:
  directory-migrations-tests-results:
    external: true
