version: "3.7"

services:
  directory-migrations-tests:
    build:
      context: ./services
      dockerfile: directory/src/FilterLists.Directory.Api/Dockerfile
      target: test-migrations
    volumes:
      - directory-migrations-tests-results:/app/tests/FilterLists.Infrastructure.Migrations.Tests/TestResults
    depends_on:
      - directory-migrations-tests-db

  directory-migrations-tests-db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DIRECTORY_DB_USER}
      POSTGRES_PASSWORD: ${DIRECTORY_DB_PASSWORD}
      POSTGRES_DB: ${DIRECTORY_DB_DATABASE}

volumes:
  directory-migrations-tests-results:
    external: true
