# overrides for development

version: "3.7"

services:
  reverse-proxy:
    ports:
      - "8080:80"
    volumes:
      - ../reverse-proxy/server-includes:/etc/nginx/server-includes:ro
      - ../reverse-proxy/location-includes:/etc/nginx/location-includes:ro
      - ../reverse-proxy/conf.d.dev:/etc/nginx/conf.d:ro
    command: ["nginx-debug", "-g", "daemon off;"]

  directory-api:
    build:
      context: ../services
      dockerfile: Directory/FilterLists.Directory.Api/dev.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  directory-db:
    command: ["postgres", "-c", "log_statement=all"]
